### ISSUE TITLE
Pip Installation Error

### ISSUE THREAD

**Issue by Florian-Konrad** [tataratat/tetgenpy#10]
Hey there,
I'm trying to install tetgenpy on Mac OS 15.1.1 in a fresh conda env using the pip command but getting the following error.
Any idea whats causing this?

```powershell
pip install tetgenpy                                          
Collecting tetgenpy
  Using cached tetgenpy-0.0.1.tar.gz (24 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /Users/konrad.florian/miniforge/envs/tet/lib/python3.13t/site-packages (from tetgenpy) (2.1.3)
Building wheels for collected packages: tetgenpy
  Building wheel for tetgenpy (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for tetgenpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [106 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-10.13-x86_64-cpython-313t/tetgenpy
      copying tetgenpy/_version.py -> build/lib.macosx-10.13-x86_64-cpython-313t/tetgenpy
      copying tetgenpy/gentet.py -> build/lib.macosx-10.13-x86_64-cpython-313t/tetgenpy
      copying tetgenpy/__init__.py -> build/lib.macosx-10.13-x86_64-cpython-313t/tetgenpy
      copying tetgenpy/plc.py -> build/lib.macosx-10.13-x86_64-cpython-313t/tetgenpy
      running build_ext
      CMake Warning:
        Ignoring extra path from command line:
      
         "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-install-y7sa65js/tetgenpy_c12de7a0962c493dade6cfe2bcaeeaf9"
      
      
      CMake Error: The source directory "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-install-y7sa65js/tetgenpy_c12de7a0962c493dade6cfe2bcaeeaf9" does not appear to contain CMakeLists.txt.
      Specify --help for usage, or press the help button on the CMake GUI.
      Traceback (most recent call last):
        File "/Users/konrad.florian/miniforge/envs/tet/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Users/konrad.florian/miniforge/envs/tet/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/konrad.florian/miniforge/envs/tet/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                              metadata_directory)
                                              ^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/build_meta.py", line 438, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/build_meta.py", line 426, in _build
          return self._build_with_temp_dir(
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^
              cmd,
              ^^^^
          ...<3 lines>...
              self._arbitrary_args(config_settings),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/build_meta.py", line 407, in _build_with_temp_dir
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 163, in <module>
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
          ~~~~~~~~~~~~~~~~~^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
          ~~~~~~~~~~~~~~~~^^^^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/command/bdist_wheel.py", line 381, in run
          self.run_command("build")
          ~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
          ~~~~~~~~~~~~~~~~^^^^^^^^^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/command/build_ext.py", line 99, in run
          _build_ext.run(self)
          ~~~~~~~~~~~~~~^^^^^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
          ~~~~~~~~~~~~~~~~~~~~~^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-build-env-6hzszx3c/overlay/lib/python3.13t/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
          ~~~~~~~~~~~~~~~~~~~~^^^^^
        File "<string>", line 151, in build_extension
        File "/Users/konrad.florian/miniforge/envs/tet/lib/python3.13t/subprocess.py", line 577, in run
          raise CalledProcessError(retcode, process.args,
                                   output=stdout, stderr=stderr)
      subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-install-y7sa65js/tetgenpy_c12de7a0962c493dade6cfe2bcaeeaf9', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/95/b981xz4s2f7d19z8rbvn1kpw0000gp/T/pip-install-y7sa65js/tetgenpy_c12de7a0962c493dade6cfe2bcaeeaf9/build/lib.macosx-10.13-x86_64-cpython-313t/tetgenpy/', '-DPYTHON_EXECUTABLE=/Users/konrad.florian/miniforge/envs/tet/bin/python3.13', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tetgenpy
Failed to build tetgenpy
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (tetgenpy)
```

**Comment by j042** [comment]
Hi!
Thanks for this issue. I also just realized that source distribution at pypi isn't complete (especially, CMakeLists.txt is missing, sorry!), which is causing this problem. It's probably better to just include 3.13 wheels. I will update those, along with some other updates (probably regarding numpy2). Maybe next weekend I can find some time.

Meanwhile, you can clone this repo and try to install it locally. Otherwise, you can try this:
```
pip install git+ssh://git@github.com/tataratat/tetgenpy.git
```

**Comment by Florian-Konrad** [comment]
Thanks for your reply.. cloning and installing locally worked!
